Repository denoland/deno_registry2, pull requests merged in 2020-09, with the labels that each got.

#103 Reland "chore: update deno to 1.3.2"
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  deps.ts
  test_deps.ts
  utils/moderation.ts
Labels: operations

#106 fix: update deno.land/x/sqs
  deps.ts
Labels: bug, high priority, operations

#108 refactor: use cloudflare provider for DNS and worker deployment
  .github/workflows/ci.yml
  README.md
  api/worker.js
  terraform/api.tf
  terraform/main.tf
  terraform/meta.tf
  terraform/providers.tf
  terraform/terraform.tfvars.example
  terraform/variables.tf
  terraform/worker.tf
  worker/package.json
  worker/wrangler.toml
Labels: operations

#109 fix: add listbucket iam permission
  .gitignore
  terraform/alerts.tf
  terraform/iam.tf
Labels: bug, high priority, operations

#110 feat: dynamic modules per owner quota
  README.md
  api/webhook/github.ts
  api/webhook/github_create_test.ts
  indexes/modules_by_owner_and_repo.json
  indexes/modules_by_repository.json
  utils/database.ts
  utils/database_test.ts
Labels: feat

#111 ops: add replication configuration
  .github/workflows/ci.yml
  terraform/iam.tf
  terraform/main.tf
  terraform/providers.tf
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: operations

#120 fix: get deno info output before getting status
  utils/deno.ts
Labels: bug, high priority, operations

#135 fix: hard crash on invalid build id
  api/builds/get.ts
  api/builds/get_test.ts
Labels: bug, high priority, operations
